#!/bin/bash

source /opt/ros/jazzy/setup.bash
source /home/pi/microros_ws/install/local_setup.bash
source /home/pi/ros_extra_ws/install/local_setup.bash
source /home/pi/turtlebro_ws/install/local_setup.bash
source /home/pi/.ros_params

ros2 launch turtlebro micro_ros_stm.xml
